version: "3"

networks:
  loki:

services:
#  flog-log:
#  image: mingrammer/flog
#  command: "-f json -t log -l -w -d 5s -o /etc/data/data.log"
#  volumes:
#    - app/logs:/logs
  fluent-bit:
    image:  grafana/fluent-bit-plugin-loki:main
    command: /fluent/bin/fluent-bit --config=/fluent-etc/fluent-bit.conf
    volumes:
      - ./fluent-conf/:/fluent-etc/:ro
      - ./app/logs:/logs
