version: "3"

networks:
  loki:

services:
#  flog-log:
#  image: mingrammer/flog
#  command: "-f json -t log -l -w -d 5s -o /etc/data/data.log"
#  volumes:
#    - app/logs:/logs
  fluent-bit:
    image:  grafana/fluent-bit-plugin-loki:main
#CMD ["/fluent-bit/bin/fluent-bit", "-e","/fluent-bit/bin/out_grafana_loki.so", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    volumes:
      - ./fluent-conf/:/fluent-etc/:ro
      - ./fluent-conf/:/fluent-bit/etc/:ro
      - ./app/logs:/logs
