version: "3"

networks:
  loki:

services:
#  flog-log:
#  image: mingrammer/flog
#  command: "-f json -t log -l -w -d 5s -o /etc/data/data.log"
#  volumes:
#    - app/logs:/logs
  fluent-bit:
    image:  grafana/fluent-bit-plugin-loki:main
#CMD ["/fluent-bit/bin/fluent-bit", "-e","/fluent-bit/bin/out_grafana_loki.so", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    volumes:
      - /github/home/fluent-conf/:/fluent-etc/:ro
      - /github/home/fluent-conf/:/fluent-bit/etc/:ro
      - /github/home/app/logs:/logs
  #docker run -d -i --name NAME --mount type=bind,src="${{ runner.temp }}/scenarios",target="/data" --entrypoint /bin/bash myImage:$VERSION
